
/* Drop Tables */

DROP TABLE T_CORP_DIST CASCADE CONSTRAINTS;
DROP TABLE T_M_CORP_CORP_PERTAINS CASCADE CONSTRAINTS;
DROP TABLE T_M_CORP_CORP_STOCK CASCADE CONSTRAINTS;
DROP TABLE T_CORP CASCADE CONSTRAINTS;
DROP TABLE T_CORP_PERTAINS CASCADE CONSTRAINTS;
DROP TABLE T_CORP_STOCK CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE T_CORP
(
	ORG number NOT NULL,
	ID number NOT NULL,
	SEQ_ID number NOT NULL,
	REG_NO varchar2(20) NOT NULL,
	CORP_NAME nvarchar2(20) NOT NULL,
	ADDR nvarchar2(20) NOT NULL,
	BELONG_ORG nvarchar2(20) NOT NULL,
	BELONG_DIST_ORG nvarchar2(15),
	BELONG_TRADE nvarchar2(20),
	ECON_KIND nvarchar2(15) NOT NULL,
	ADMIT_MAIN nvarchar2(15),
	START_DATE date NOT NULL,
	CHECK_DATE date,
	OPER_MAN_IDENT_NO varchar2(20) NOT NULL,
	OPER_MAN_NAME varchar2(10) NOT NULL,
	CORP_STATUS number NOT NULL,
	REG_CAPI number,
	FARE_TERM_START date NOT NULL,
	FARE_TERM_END nvarchar2(10) NOT NULL,
	FARE_SCOPE nvarchar2(200),
	UNI_SCID varchar2(20) NOT NULL,
	TEL varchar2(15),
	WEB_URL varchar2(30),
	EMAIL varchar2(30),
	PRAC_PERSON_NUM number,
	ORG_INST_CODE varchar2(15) NOT NULL,
	TAXPAY_NUM varchar2(20) NOT NULL,
	STAFF_SIZE varchar2(15),
	ENGLISH_NAME varchar2(20),
	FORMER_NAME varchar2(20),
	CREATE_DATE date,
	CREATE_ORG number NOT NULL,
	PRIMARY KEY (ORG, ID, SEQ_ID)
);


CREATE TABLE T_CORP_DIST
(
	SUB_ORG number NOT NULL,
	SUB_ID number NOT NULL,
	SUB_SEQ_ID number NOT NULL,
	DIST_REG_NO varchar2(20) NOT NULL,
	DIST_NAME nvarchar2(20) NOT NULL,
	DIST_BELONG_ORG nvarchar2(20) NOT NULL,
	DIST_ORG number NOT NULL,
	DIST_ID number NOT NULL,
	DIST_SEQ_ID number NOT NULL,
	FARE_PLACE nvarchar2(20),
	OPER_MAN_IDENT_NO varchar2(20) NOT NULL,
	OPER_MAN_NAME nvarchar2(5) NOT NULL,
	FARE_SCOPE nvarchar2(30),
	START_DATE date,
	CHECK_DATE date NOT NULL,
	CREATE_DATE date,
	PRIMARY KEY (SUB_ORG, SUB_ID, SUB_SEQ_ID)
);


CREATE TABLE T_CORP_PERTAINS
(
	SUB_ORG number NOT NULL,
	SUB_ID number NOT NULL,
	SUB_SEQ_ID number NOT NULL,
	CERTIFICATE_TYPE nvarchar2(6) NOT NULL,
	PERSON_NAME nvarchar2(5) NOT NULL,
	PERSON_TYPE nvarchar2(5),
	CERTIFICATE_NO varchar2(18) NOT NULL,
	SELECT_TYPE nvarchar2(5),
	HOLDPOST_START date,
	HOLDPOST_END date,
	SEX varchar2(5),
	AGE number,
	COUNTRY nvarchar2(5),
	CREATE_DATE date,
	PRIMARY KEY (SUB_ORG, SUB_ID, SUB_SEQ_ID)
);


CREATE TABLE T_CORP_STOCK
(
	SUB_ORG number NOT NULL,
	SUB_ID number NOT NULL,
	SUB_SEQ_ID number NOT NULL,
	SUB_STOCK_TYPE varchar2(10) NOT NULL,
	COUNTRY varchar2(10),
	CERTIFICATE_TYPE varchar2(10) NOT NULL,
	CERTIFICATE_NO varchar2(20) NOT NULL,
	STOCK_NAME varchar2(10) NOT NULL,
	STOCK_CAPI_TYPE varchar2(10),
	STOCK_CAPI float,
	STOCK_CAPI_DOLLAR float,
	STOCK_CAPI_RMB float,
	STOCK_PERCENT varchar2(8),
	STOCK_RATE_RMB float,
	STOCK_RATE_DOLLAR float,
	CREATE_DATE date,
	PRIMARY KEY (SUB_ORG, SUB_ID, SUB_SEQ_ID)
);


CREATE TABLE T_M_CORP_CORP_PERTAINS
(
	ORG number NOT NULL,
	ID number NOT NULL,
	SEQ_ID number NOT NULL,
	SUB_ORG number NOT NULL,
	SUB_ID number NOT NULL,
	SUB_SEQ_ID number NOT NULL
);


CREATE TABLE T_M_CORP_CORP_STOCK
(
	ORG number NOT NULL,
	ID number NOT NULL,
	SEQ_ID number NOT NULL,
	SUB_ORG number NOT NULL,
	SUB_ID number NOT NULL,
	SUB_SEQ_ID number NOT NULL
);



/* Create Foreign Keys */

ALTER TABLE T_CORP_DIST
	ADD FOREIGN KEY (DIST_ORG, DIST_ID, DIST_SEQ_ID)
	REFERENCES T_CORP (ORG, ID, SEQ_ID)
;


ALTER TABLE T_M_CORP_CORP_PERTAINS
	ADD FOREIGN KEY (ORG, ID, SEQ_ID)
	REFERENCES T_CORP (ORG, ID, SEQ_ID)
;


ALTER TABLE T_M_CORP_CORP_STOCK
	ADD FOREIGN KEY (ORG, ID, SEQ_ID)
	REFERENCES T_CORP (ORG, ID, SEQ_ID)
;


ALTER TABLE T_M_CORP_CORP_PERTAINS
	ADD FOREIGN KEY (SUB_ORG, SUB_ID, SUB_SEQ_ID)
	REFERENCES T_CORP_PERTAINS (SUB_ORG, SUB_ID, SUB_SEQ_ID)
;


ALTER TABLE T_M_CORP_CORP_STOCK
	ADD FOREIGN KEY (SUB_ORG, SUB_ID, SUB_SEQ_ID)
	REFERENCES T_CORP_STOCK (SUB_ORG, SUB_ID, SUB_SEQ_ID)
;



